Feature/product compare
moe-mohammed/KnowBetter pull request #45
Opened 2021-12-04 20:06 UTC by jraobc

2021-12-05 05:35 UTC, moe-mohammed requested changes
All the changes I requested are all about relevance. How code is relevant to the pull request, and how code is written in a way that is relevant to what it's doing. Please make sure that going forward in all code contributions that code is always relevant.

2021-12-05 05:35 UTC, moe-mohammed commented on KnowBetter-WebApp/Views/Products/CompareProductSelect.cshtml
> +    function myFunction() {
change function name to show what it really means. ToggleDropdownVisibility() could be an example, and you could remove the comments with this change since the function says what it does.

2021-12-05 05:35 UTC, moe-mohammed commented on KnowBetter-WebApp/Views/Products/CompareProductSelect.cshtml
> +    function filterFunction() {
change to filterProducts(), the word function is redundant and lacks description

2021-12-05 05:35 UTC, moe-mohammed commented on KnowBetter-WebApp/Views/Products/CompareProductSelect.cshtml
> +        a = div.getElementsByTagName("a");
change a to anchorElementsArray to make mroe sense of what's going on

2021-12-05 05:35 UTC, moe-mohammed commented on KnowBetter-WebApp/Views/Products/CompareProductSelect.cshtml
> +        filter = input.value.toUpperCase();
change variable name and shorten it to
searchInput = document.getElementById("myInput").value.toUpperCase();
also change the elements id from myInput to searchInput

2021-12-05 05:35 UTC, moe-mohammed commented on KnowBetter-WebApp/Views/Products/CompareProductSelect.cshtml
> +    function myFunction() {
make sure the onclick in button element is updated to the new name

2021-12-05 05:37 UTC, moe-mohammed commented on KnowBetter-WebApp/Controllers/ProductsController.cs
> +            }
this is not necessary for now, but in the future always add a space after closing braces. 
such as: foreach() {} <line of white space> <more code>
it's generally just nice code etiquette and makes code more readable

2021-12-05 06:05 UTC, moe-mohammed requested changes

2021-12-05 07:29 UTC, moe-mohammed requested changes

2021-12-05 07:29 UTC, moe-mohammed commented on KnowBetter-WebApp/Views/Shared/UI_Layout.cshtml
> +                    <li><a href="@Url.Action("CompareProductSelect","Products")" style="color:white">Compare Product</a></li>
remove testing code

2021-12-05 07:42 UTC, moe-mohammed commented on KnowBetter-WebApp/wwwroot/css/UI_StyleSheet.css
> +.dbbtnclass {
let's discuss this in our meeting

2021-12-06 01:20 UTC, jraobc commented on KnowBetter-WebApp/Controllers/IngredientsController.cs
> +
Will fix in next commit

2021-12-06 01:20 UTC, jraobc commented on KnowBetter-WebApp/Controllers/HomeController.cs
> +
Will fix in next commit

2021-12-06 01:20 UTC, jraobc commented on KnowBetter-WebApp/Models/Product.cs
> +
Will fix in next commit

2021-12-06 01:20 UTC, jraobc commented on KnowBetter-WebApp/Models/Product.cs
> +
Will fix whitespace in next commit

2021-12-06 01:32 UTC, jraobc commented on KnowBetter-WebApp/Views/Shared/UI_Layout.cshtml
> +                    <li><a href="@Url.Action("CompareProductSelect","Products")" style="color:white">Compare Product</a></li>
This isn't testing code. Unsure what this change is requesting. Are we not going to have links to the compare product view in the navbar?

2021-12-06 23:19 UTC, moe-mohammed approved these changes

2021-12-06 23:19 UTC, merged